{
    'name': 'Student Management',
    'version': '1.0',
    'summary': 'Module to manage student records',
    'description': 'Module to manage student records with unique sequence numbers, automatic age calculation, logging, and access rights.',
    'author': 'Jivika Khadka',
    'depends': ['base', 'mail','website'],
    'category': 'Education',
    'data': [
        'security/ir.model.access.csv',
        'views/student_views.xml',
        'views/student_record_history.xml',
        'data/student_sequence.xml',
        'reports/report_template.xml',
        'reports/student_id_card.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
